// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapp.DB.Models;

#nullable disable

namespace webapp.DB.Migrations
{
    [DbContext(typeof(WEBAPPDBCONTEXT))]
    [Migration("20230815102053_MigrationFinal4")]
    partial class MigrationFinal4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webapp.DB.Models.EmployeeCardDetails", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Guid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("CardIssueDate")
                        .HasColumnType("DATE");

                    b.Property<string>("LoanId")
                        .IsRequired()
                        .HasColumnType("Guid");

                    b.HasKey("EmployeeId");

                    b.ToTable("EmployeeCardDetails");
                });

            modelBuilder.Entity("webapp.DB.Models.EmployeeIssueDetails", b =>
                {
                    b.Property<int>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Guid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IssueId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("Guid");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("DATE");

                    b.Property<int>("LoanId")
                        .HasColumnType("Guid");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("DATE");

                    b.HasKey("IssueId");

                    b.ToTable("employeeIssueDetails");
                });

            modelBuilder.Entity("webapp.DB.Models.EmployeeMaster", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Guid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("DateOfJoining")
                        .HasColumnType("DATE");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.HasKey("EmployeeId");

                    b.ToTable("EmployeeMaster");
                });

            modelBuilder.Entity("webapp.DB.Models.ItemDB", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Guid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("IssueStatus")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("ItemCategory")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("ItemMake")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<int>("ItemValue")
                        .HasColumnType("int(6)");

                    b.HasKey("ItemId");

                    b.ToTable("ItemDB");
                });

            modelBuilder.Entity("webapp.DB.Models.LoanCardMaster", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("guid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanId"));

                    b.Property<int>("Duration")
                        .HasColumnType("int(2)");

                    b.Property<string>("LoanType")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("LoanId");

                    b.ToTable("LoanCardMaster");
                });
#pragma warning restore 612, 618
        }
    }
}
