// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapp.DB.Models;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(WEBAPPDBCONTEXT))]
    [Migration("20230814015149_MigrationFinal2")]
    partial class MigrationFinal2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webapp.DB.Models.EmployeeMaster", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Guid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.HasKey("EmployeeId");

                    b.ToTable("EmployeeMaster");
                });

            modelBuilder.Entity("webapp.DB.Models.ItemDB", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Guid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("IssueStatus")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("ItemCategory")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("ItemMake")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<int>("ItemValue")
                        .HasColumnType("int(6)");

                    b.HasKey("ItemId");

                    b.ToTable("ItemDB");
                });
#pragma warning restore 612, 618
        }
    }
}
